services:
  postgres:
    image: postgres:16
    container_name: calorietracker-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: calorietracker
    ports:
      - "5432:5432"
    volumes:
      - calorietracker_pg_data:/var/lib/postgresql/data
volumes:
  calorietracker_pg_data:
